ethereum_jsonrpc:
  host: https://cloudflare-eth.com
  version: 2.0
general:
  processing: sync
  approach: greedy
  storage: memory
http:
  host: 0.0.0.0
  port: 8080
storage:
  redis:
    host: localhost:6379
    password: ""
    db: 0

    data_keep_alive_duration: 3h
